# Generated by Django 2.0.6 on 2018-12-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalitem',
            name='goal_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.GoalList'),
        ),
    ]
